package eu.arcadia.expertsystem.rules 

import eu.arcadia.expertsystem.facts.*

declare  MonitoredComponent 
    @role( event )
    @expires( 10m )

end


rule "Sound the alarm in case temperature rises above threshold"
when
 
$a :Number(doubleValue > 50) from accumulate(
            $e: MonitoredComponent(name== "FFFFFE1", metric== "memory_total") over window:time(5s) from entry-point "MonitoringStream",
            sum( $e.getValue()))
then
    System.out.println("footesttthere"+$a);
end



rule "5a0ae56c4f0c038e6475d038"
when
    
    $tot0 := java.lang.Double( $tot0 >=1 ) from accumulate(     
    $m0 := MonitoredComponent( name== "3d020fef-cd87" && metric== "CPULoad" ) over window:time(1m)from entry-point "MonitoringStream" ,
        average( $m0.getValue() )  )  
then
    insertLogical( new Action("5a0ae58d4f0c038e6475d049","3d020fef-cd87",RuleActionType.IAAS_MANAGEMENT,"1","add_ram(GB)")); 

end

